CREATE TABLE User_info_family
(
	FmName VARCHAR(50) NOT NULL,
	USERNAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(40) NOT NULL,
	PASS NVARCHAR(50) NOT NULL
);

SELECT * FROM User_info_family

DROP TABLE User_info_family
