CREATE TABLE MISSION (
Uni_id NVARCHAR (50) NOT NULL,
MISSION_NAME VARCHAR (50) NOT NULL,
Statuss VARCHAR (50) NULL
);

INSERT INTO MISSION VALUES ('20419911', 'OML', 'MIA');
INSERT INTO MISSION VALUES ('20425851', 'OLMS', 'Active');
INSERT INTO MISSION VALUES ('20430681', 'OTL', 'KIA');
INSERT INTO MISSION VALUES ('20000000', 'OLMS', 'Active');

SELECT * FROM MISSION